---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
  - directory: "/"
    package-ecosystem: "github-actions"
    open-pull-requests-limit: 99
    schedule:
      interval: "daily"
...
