---
addons:
  apt:
    packages:
    - docker-ce
    sources:
    - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
      key_url: 'https://download.docker.com/linux/ubuntu/gpg'

dist: xenial

env:
  global:
    - DOCKER_BUILDX_DIR_PATH="${HOME}/.docker/cli-plugins"
    - DOCKER_BUILDX_PATH="${DOCKER_BUILDX_DIR_PATH}/docker-buildx"
    - DOCKER_CLI_EXPERIMENTAL=enabled

language: minimal

services:
  - docker

script:
  - docker version
  - docker buildx ls
