---
addons:
  apt:
    packages:
    - docker-ce
    sources:
    - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
      key_url: 'https://download.docker.com/linux/ubuntu/gpg'

before_install:
  - docker run --privileged linuxkit/binfmt:v0.7

dist: xenial

env:
  global:
    - DOCKER_BUILDX_DIR_PATH="${HOME}/.docker/cli-plugins"
    - DOCKER_BUILDX_PATH="${DOCKER_BUILDX_DIR_PATH}/docker-buildx"
    - DOCKER_CLI_EXPERIMENTAL=enabled

language: minimal

services:
  - docker

script:
  - docker version
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
  - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ferrarimarco/pxe:latest --load .
  - docker buildx imagetools inspect ferrarimarco/pxe:latest
