---
addons:
  apt:
    packages:
    - docker-ce
    sources:
    - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) nightly'
      key_url: 'https://download.docker.com/linux/ubuntu/gpg'

dist: xenial

language: minimal

services:
  - docker

script:
  - docker version
  - docker buildx ls
